apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: cassandra
    spec:
      containers:
        - env:
            - name: CASSANDRA_CLUSTER_NAME
              value: citizix
            - name: CASSANDRA_KEYSPACE
              value: Messaging
          image: cassandra
          name: cassandra
          ports:
            - containerPort: 9042
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra-claim0
            - mountPath: /docker-entrypoint-initdb.d/
              name: cassandra-claim1
      restartPolicy: Always
      volumes:
        - name: cassandra-claim0
          persistentVolumeClaim:
            claimName: cassandra-claim0
        - name: cassandra-claim1
          persistentVolumeClaim:
            claimName: cassandra-claim1
status: {}
