apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  ports:
    - name: "9042"
      port: 9042
      targetPort: 9042
  selector:
    io.kompose.service: cassandra
status:
  loadBalancer: {}
